# ==============================================================================
# SOVEREIGN SHINY BUILDER (FULL INTEGRATION)
# Path: ./03_reporting_engine/05_shiny_builder.R
# ==============================================================================

build_and_launch_shiny <- function(base_path) {
  dashboard_path <- file.path(base_path, "03_reporting_engine", "etf123_dashboard.Rmd")
  
  rmd_content <- c(
    "---",
    "title: 'Sovereign ETF Intelligence'",
    "runtime: shiny",
    "output: ",
    "  flexdashboard::flex_dashboard:",
    "    orientation: rows",
    "    vertical_layout: fill",
    "    theme: {version: 4, bg: '#FFF1E0', fg: '#4D4D4D', primary: '#2e86c1'}",
    "---",
    "",
    "```{r setup, include=FALSE}",
    "library(flexdashboard); library(tidyverse); library(xts); library(here); library(shiny); library(scales); library(ggrepel); library(PerformanceAnalytics)",
    "base_path <- here()",
    "source(file.path(base_path, '00_etf_data_download', '01_init_universe.R'))",
    "source(file.path(base_path, '03_reporting_engine', '03_advanced_visuals.R'))",
    "raw_xts <- readRDS(file.path(base_path, 'data_processed', 'signal_table.rds'))",
    "signal_table <- xts(coredata(raw_xts), order.by = as.Date(index(raw_xts)))",
    "tclass(signal_table) <- 'Date'",
    "```",
    "",
    "Sidebar {.sidebar}",
    "=====================================",
    "### 🎛️ Global Filters",
    "```{r, echo=FALSE}",
    "selectInput('category', 'Asset Class Focus:', choices = c('All', unique(etf_metadata$category)))",
    "dateRangeInput('dates', 'Analysis Horizon:', start = Sys.Date()-365, end = Sys.Date())",
    "sliderInput('sigma_win', 'Z-Score Window (Days):', min = 20, max = 500, value = 252)",
    "hr()",
    "### 🔍 Efficiency Zoom",
    "sliderInput('risk_zoom', 'Risk Range (Vol %):', min = 0, max = 150, value = c(0, 60), post = '%')",
    "sliderInput('ret_zoom', 'Return Range (Ann %):', min = -100, max = 200, value = c(-30, 80), post = '%')",
    "```",
    "",
    "Analytical Sigma",
    "=====================================",
    "Row {data-height=150}",
    "-----------------------------------------------------------------------",
    "### Max Sigma Ticker",
    "```{r, echo=FALSE}",
    "sigma_data <- reactive({",
    "  data_sub <- if(input$category == 'All') signal_table else signal_table[, etf_metadata$ticker[etf_metadata$category == input$category]]",
    "  data_sub <- data_sub[paste0(input$dates[1], '/', input$dates[2])]",
    "  get_sigma_scores(data_sub, etf_metadata, window = input$sigma_win)",
    "})",
    "",
    "renderValueBox({",
    "  res <- sigma_data()",
    "  if(nrow(res) == 0) return(valueBox('N/A', caption = 'No Data', color='gray'))",
    "  top <- res %>% slice(1)",
    "  valueBox(top$ticker, caption = paste('Max Shock (Z:', round(top$z_score, 2), ')'), icon='fa-bolt', color='#c0392b')",
    "})",
    "```",
    "",
    "Row {data-height=850}",
    "-----------------------------------------------------------------------",
    "### 📊 Sigma Disruption Analysis",
    "```{r, echo=FALSE}",
    "renderPlot(res = 120, { plot_sigma_analysis(sigma_data()) })",
    "```",
    "",
    "Optical Momentum",
    "=====================================",
    "Row {data-height=1000}",
    "-----------------------------------------------------------------------",
    "### 🕒 Momentum Heatmap",
    "```{r, echo=FALSE}",
    "renderPlot(res = 120, {",
    "  data_sub <- if(input$category == 'All') signal_table else signal_table[, etf_metadata$ticker[etf_metadata$category == input$category]]",
    "  plot_optical_overview(list(d = data_sub), etf_metadata)",
    "})",
    "```",
    "",
    "Precision YTD",
    "=====================================",
    "Row {data-height=1000}",
    "-----------------------------------------------------------------------",
    "### 🎯 Year-to-Date Performance",
    "```{r, echo=FALSE}",
    "renderPlot(res = 120, {",
    "  data_sub <- if(input$category == 'All') signal_table else signal_table[, etf_metadata$ticker[etf_metadata$category == input$category]]",
    "  plot_precision_ytd(data_sub, etf_metadata)",
    "})",
    "```",
    "",
    "Risk-Reward Efficiency",
    "=====================================",
    "Row {data-height=1000}",
    "-----------------------------------------------------------------------",
    "### 🌀 Efficiency Frontier",
    "```{r, echo=FALSE}",
    "renderPlot(res = 120, {",
    "  data_sub <- if(input$category == 'All') signal_table else signal_table[, etf_metadata$ticker[etf_metadata$category == input$category]]",
    "  data_sub <- data_sub[paste0(input$dates[1], '/', input$dates[2])]",
    "  current_limits <- list(risk = input$risk_zoom / 100, ret = input$ret_zoom / 100)",
    "  plot_synthetic_efficiency(data_sub, etf_metadata, limits = current_limits)",
    "})",
    "```"
  )
  
  writeLines(rmd_content, dashboard_path)
  rmarkdown::run(dashboard_path)
}