---
title: "Sovereign ETF Intelligence Dossier"
date: "2026-03-07"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme: 
      version: 4
      bg: "#FFF1E0"
      fg: "#4D4D4D" 
      primary: "#2e86c1"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)


# 1. LOAD LIBRARIES
library(flexdashboard)
library(tidyverse)
library(xts)
library(tidyquant)
library(scales)
library(ggrepel)
library(here)

# 2. PATH ANCHOR
base_path <- here()

# 3. LOAD EXTERNAL LOGIC
source(file.path(base_path, "00_etf_data_download", "01_init_universe.R"))
source(file.path(base_path, "03_reporting_engine", "03_advanced_visuals.R"))

# 4. LOAD & REPAIR DATA
raw_xts <- readRDS(file.path(base_path, "data_processed", "signal_table.rds"))
signal_table <- xts(coredata(raw_xts), order.by = as.Date(index(raw_xts)))
tclass(signal_table) <- "Date"

```



Row {data-height=600}
📊 Analytical View: Sigma Disruption (Z-Score)



```{r cars}
# Renders the bar plot with 4-Sigma cap and text labels at the end
plot_sigma_analysis(signal_table, etf_metadata)


```




```{r x1, echo=FALSE}

```

```{r x2, echo=FALSE}


```

```{r x3, echo=FALSE}

```

```{r x4, echo=FALSE}


```

```{r x5, echo=FALSE}


```

```{r x6, echo=FALSE}



```

```{r x7, echo=FALSE}



```

```{r x8, echo=FALSE}

```

```{r x9, echo=FALSE}

```

```{r x10, echo=FALSE}

```

```{r x11, echo=FALSE}

```

```{r x12, echo=FALSE}

```
